@startuml Speech Notetaker Outline

actor User

User --> (Main Thread "UI") : Launch application\n Initialize

(Main Thread "UI") --> (UI Display) : Main Thread\nInitialize UI
(Main Thread "UI") --> (Recording Thread) :  On start_recording\n initializes 
(Main Thread "UI") --> (Transcription Thread) :  On stop_recording\n initializes 

(Recording Thread) --> (Sound Device Thread) : Initializes
(Recording Thread) --> (Whisper Thread) : Initializes
(Sound Device Thread) --> [Audio Queue] : Sends audio chunks
[Audio Queue] --> (Sound Device Thread) : Dequeues
(Sound Device Thread) --> [Transcription Queue] : If is_recording True\n enqueus 

[Transcription Queue] --> (Whisper Thread)  : Dequeues if audio chunks available
(Whisper Thread) --> [Live Text UI Queue] : Enqueus transcribed audio chunks
(Whisper Thread) --> [saved_block] : Appends all transcribed text \n blocks in order
[saved_block] --> (Transcription Thread) : After Whisper finished \n dequeues
(Transcription Thread) --> (API Request for Ollama qwen2.5) : Sent saved_block with prompt
(API Request for Ollama qwen2.5) --> [cleaned_notes] : Receives API request\n refine() formates into cleaned notes
[cleaned_notes] --> (Main Thread "UI") : Dequeues
[Live Text UI Queue] --> (Main Thread "UI") : Dequeues
(Main Thread "UI") --> (UI Display) : Appends live text in real time

(cleaned_notes) --> (UI Display) : Displays cleaned notes
(cleaned_notes) --> (Save Text) : Option to save cleaned notes to .txt file

package "Notes" {
  (Python 3.10 / 3.11 supported)
  (Ollama qwen2.5-7b on local machine)
}

@enduml
